version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile  
    environment:
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_NAME_TEST: ${DB_NAME_TEST}
      DB_NAME_PRODUCTION: ${DB_NAME_PRODUCTION}
    ports:
      - "3000:3000" 
    depends_on:
      - db
    command: ["./wait-for-it.sh", "${DB_HOST}", "${DB_PORT}"]

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: