default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000
  host: <%= ENV['DB_HOST'] %>
  port: <%= ENV['DB_PORT'] || 5432 %>
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>



development:
  <<: *default
  database: <%= ENV['DB_NAME'] || 'my_test_task_app_development' %>

test:
  <<: *default
  database: <%= ENV['DB_NAME_TEST'] || 'my_test_task_app_test' %>


production:
  <<: *default
  database: <%= ENV['DB_NAME_PRODUCTION'] || 'my_test_task_app_production' %>